# Classification metrics

## accuracy score

In [2]:


import numpy as np
from sklearn.metrics import accuracy_score

y_pred = [0,2,1,3]
y_true = [0,1,2,3]

accuracy_score(y_true, y_pred)

0.5

In [9]:
# normalize gives the number of 'correctly' classified sample 
accuracy_score(y_true, y_pred, normalize =False)

2

In [3]:
# multilabel case

np.ones((2,2,)) # Predicted

array([[1., 1.],
       [1., 1.]])

In [6]:
np.array(([0,1],[1,1]))  # true

array([[0, 1],
       [1, 1]])

In [7]:
# accuracy_score(y_true, y_pred, *, normalize=True, sample_weight=None)
accuracy_score(np.array(([0,1],[1,1])),np.ones((2,2,)))

0.5

## Confusion matrix

In [12]:
from sklearn.metrics import confusion_matrix

In [15]:
y_true = [2, 0, 2, 2, 0, 1]
y_pred = [0, 0, 2, 2, 0, 2]

'''confusion_matrix(
    y_true,
    y_pred,
    *,
    labels=None,
    sample_weight=None,
    normalize=None,
)'''


confusion_matrix(y_true, y_pred)


array([[2, 0, 0],
       [0, 0, 1],
       [1, 0, 2]], dtype=int64)

In [16]:
# parameter normalize allow you to report ration instead of counts
confusion_matrix(y_true, y_pred, normalize= 'all')

array([[0.33333333, 0.        , 0.        ],
       [0.        , 0.        , 0.16666667],
       [0.16666667, 0.        , 0.33333333]])

In [17]:
4/6

0.6666666666666666

## classification report

In [20]:
# builds a text report
from sklearn.metrics import classification_report

y_true = [0,1,2,2,0]
y_pred = [0,0,2,1,0] 

target_names = ['class 0', 'class 1', 'class 2']
print(classification_report(y_true, y_pred, target_names= target_names))
print(f'Accuracy score from accuracy matrix {accuracy_score(y_true, y_pred)}')

              precision    recall  f1-score   support

     class 0       0.67      1.00      0.80         2
     class 1       0.00      0.00      0.00         1
     class 2       1.00      0.50      0.67         2

    accuracy                           0.60         5
   macro avg       0.56      0.50      0.49         5
weighted avg       0.67      0.60      0.59         5

Accuracy score from accuracy matrix 0.6


In [21]:
# Precision:
# is the ability of the classifier not to label as +ve a sample that is -ve

# recall:
# is the ability of the classifier to fine all the +ve sample

In [24]:
from sklearn import metrics

y_pred = [0, 1, 0, 0]
y_true = [0, 1, 0, 1]


print(classification_report(y_true, y_pred))

              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      0.50      0.67         2

    accuracy                           0.75         4
   macro avg       0.83      0.75      0.73         4
weighted avg       0.83      0.75      0.73         4



In [25]:
confusion_matrix(y_true, y_pred)


array([[2, 0],
       [1, 1]], dtype=int64)

In [27]:
metrics.precision_score(y_true, y_pred)
# Precision = TP / TP + FP


1.0

In [28]:
metrics.recall_score(y_true, y_pred)
# recall = TP / TP + FN

0.5

In [29]:
metrics.f1_score(y_true, y_pred)

0.6666666666666666

In [31]:
# beta = 0.5
metrics.fbeta_score(y_true, y_pred, beta = 0.5)

0.8333333333333334

In [32]:
# beta = 1
metrics.fbeta_score(y_true, y_pred, beta = 1)

0.6666666666666666

In [33]:
# beta = 2
metrics.fbeta_score(y_true, y_pred, beta = 2)

0.5555555555555556

## Receiver operating characteristic (ROC)
## Area under curve (AUC)